### ISSUE TITLE
support depth in pipeline

### ISSUE THREAD

**Issue by alon** [rukai/vulkano-text#1]
First of all thanks for the awesome addition to vulkano! I'm playing with vulkano and now vulkano-text to make a molecule viewer and I needed to patch the pipeline definition in vulkano-text since there must be a match between the pipeline used by vulkano-text and the one used by the caller. Of course the change I did is awful since you would want to support any number of pipelines. Maybe use a template for it? not sure what the right approach is, but would be glad to write a patch if you would suggest an avenue.

https://github.com/alon/vulkano-text/commit/61659bb6521237077b3086b28c6dcd7aa2426c18

Problem without patch:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AutoCommandBufferBuilderContextError(IncompatibleRenderPass)', /checkout/src/libcore/result.rs:906:4
s

Relevant part from the stack trace:

  11: vulkano_text::DrawText::draw_text
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano_text-0.5.0/src/lib.rs:276
  12: <vulkano::command_buffer::auto::AutoCommandBufferBuilder as vulkano_text::DrawTextTrait>::draw_text
             at /home/hiro/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano_text-0.5.0/src/lib.rs:293

**Comment by rukai** [comment]
Thanks for reporting the issue.

Sorry it took so long to reply, for some reason github wasnt set to "watching" for this repository. Not sure why...

By sheer coincidince, it seems I fixed this issue 2 days after you posted this issue without even seeing it. :D
